const colors = [
    { code: "#FF0000", name: "Red" },
    { code: "#00FF00", name: "Green" },
    { code: "#0000FF", name: "Blue" },
    { code: "#FFFF00", name: "Yellow" },
    { code: "#FF00FF", name: "Magenta" },
    { code: "#00FFFF", name: "Cyan" },
    { code: "#800000", name: "Maroon" },
    { code: "#808000", name: "Olive" },
    { code: "#008000", name: "Dark Green" },
    { code: "#800080", name: "Purple" },
    { code: "#008080", name: "Teal" },
    { code: "#000080", name: "Navy" },
    { code: "#FFA500", name: "Orange" },
    { code: "#A52A2A", name: "Brown" },
    { code: "#8B0000", name: "Dark Red" },
    { code: "#32CD32", name: "Lime Green" },
    { code: "#FFD700", name: "Gold" },
    { code: "#4B0082", name: "Indigo" },
    { code: "#EE82EE", name: "Violet" },
    { code: "#F0E68C", name: "Khaki" },
    { code: "#D2B48C", name: "Tan" },
    { code: "#FF6347", name: "Tomato" },
    { code: "#4682B4", name: "Steel Blue" },
    { code: "#D2691E", name: "Chocolate" },
    { code: "#1E90FF", name: "Dodger Blue" },
    { code: "#ADFF2F", name: "Green Yellow" },
    { code: "#FF1493", name: "Deep Pink" },
    { code: "#00CED1", name: "Dark Turquoise" },
    { code: "#20B2AA", name: "Light Sea Green" },
    { code: "#B8860B", name: "Dark Golden Rod" },
    { code: "#2F4F4F", name: "Dark Slate Gray" },
    { code: "#8B4513", name: "Saddle Brown" },
    { code: "#5F9EA0", name: "Cadet Blue" },
    { code: "#D3D3D3", name: "Light Grey" },
    { code: "#90EE90", name: "Light Green" },
    { code: "#FFDAB9", name: "Peach Puff" },
    { code: "#FFB6C1", name: "Light Pink" },
    { code: "#7B68EE", name: "Medium Slate Blue" },
    { code: "#6A5ACD", name: "Slate Blue" },
    { code: "#708090", name: "Slate Gray" }
];
